### ISSUE TITLE
How to test the MQTT-SN

### ISSUE THREAD

**Issue by RafaelMarin81** [adamrenner/mqtt-sn-tools-contiki#3]
Hi

I am trying to test MQTT-SN in contiki using a msp430 mote.
To do that, I use the broker called "Mosquitto" in a computer. And I use the uip6-bridge of Contiki to communicate the 6lowpan sensor network with PC computer.

However, I check that the mote sends the messages towards the IPv6 of PC where Mosquitto-broker is running in port 1883. The message is shown by wireshark in the PC.
But there is not any response from Mosquitto-broker.

Please, could you say the broker compatible with the implementation of MQTT-SN in contiki??
How do you test the MQTT-SN client of contiki??

Best regards,
Rafa

**Comment by adamrenner** [comment]
Rafa,
At the time that I worked on this, Mosquitto had still not implemented MQTT-SN.
However, the developers of RSMB had released an open source version as they are planning to combine efforts with mosquitto. This version of RSMB was working with the contiki application.
http://git.eclipse.org/c/mosquitto/org.eclipse.mosquitto.rsmb.git/
It compiles to multiple executables. You will want to use the broker_mqttsn.
Also, the config file can be a bit tricky.
Best,
Adam

**Comment by jluzuria2001** [comment]
Hi all,

I'm trying to use the [mqtt-sn-tools-contiki] of adamrenner with Z1 board of zolertia
with another Z1 (running a border-router example that routes all the IP packets from a Linux machine to wireless devices and viceversa) attached to RPi as a gateway [http://git.eclipse.org/c/paho/org.eclipse.paho.mqtt-sn.apps.git].

Currently I use with the sub/pub clients offered on mqttsn-tools over linux and work fine. 
But when I use it with the mote board I'm getting problems with the "length of the packet" then "the connection is lost" (as is shown in the attached image )

![problem](https://cloud.githubusercontent.com/assets/1404764/14790347/2719baf6-0b11-11e6-9a8c-e888ca8c11d1.png)

Has somebody observed this behavior or any hints how to resolve this?
Thanks in advance.
